import legacyWorker from "../src/tradingview_core_wrapper.js";

const BRAND = "ReFo . EGX Smart Trader";
const DEFAULT_WEBAPP = "https://refogx-pro.folkhero3.workers.dev/";
const MENU={keyboard:[["🖥️ الشاشة اللحظية","🤖 المساعد الذكي"],["💳 اشترك الآن / ترقية"],["📈 أسهم المضاربة اليومية","📊 الصفقات"],["📈 تحليل الأسهم","♟️ التحليل المتقدم"],["🎯 فرص اليوم","🚀 الإشارات النشطة"],["📋 قائمة المتابعة","🚨 تنبيهاتي"],["💼 محفظتي","📈 تقرير الأداء"],["🗺️ السوق والقطاعات","⚙️ الإعدادات"]],resize_keyboard:true,is_persistent:true};
const ALIASES=new Map([["📈 تحليل الأسهم","🔍 تحليل سهم"],["📈 أسهم المضاربة اليومية","🎯 فرص اليوم"],["📊 الصفقات","🚀 الإشارات النشطة"],["📋 قائمة المتابعة","🚨 تنبيهاتي"],["♟️ التحليل المتقدم","🧠 التحليل المتقدم"],["⚙️ الإعدادات","/menu"],["💳 اشترك الآن / ترقية","💳 اشتراك / ترقية"],["🗺️ السوق والقطاعات","🗺️ أداء القطاعات"]]);
function token(e){return e.TELEGRAM_BOT_TOKEN||e.TOKEN||""}
function gate(e){return e.TELEGRAM_CHAT_ID||e.CHAT_ID||""}
function legacyEnv(e){return Object.assign({},e,{TOKEN:e.TOKEN||e.TELEGRAM_BOT_TOKEN,CHAT_ID:e.CHAT_ID||e.TELEGRAM_CHAT_ID})}
function api(e,m){return `https://api.telegram.org/bot${token(e)}/${m}`}
async function send(e,c,t,r){const b={chat_id:String(c),text:t,parse_mode:"HTML",disable_web_page_preview:true};if(r)b.reply_markup=r;const x=await fetch(api(e,"sendMessage"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});if(!x.ok)throw new Error(`Telegram sendMessage failed: ${x.status}`)}
async function showMenu(e,c){await send(e,c,`📈 <b>${BRAND}</b>\n\nمساعد قرار وتحليل للسوق المصري.\nاختر من القائمة الرئيسية.\n\n⚠️ البيانات المتأخرة تظل معلّمة بوضوح ولا تُعامل كلحظية.`,MENU)}
async function showLive(e,c){const url=e.REFO_WEBAPP_URL||DEFAULT_WEBAPP;await send(e,c,"🖥️ <b>ReFo EGX Terminal Pro</b>\n\nمنصة التداول والتحليل المتقدمة متاحة الآن.\nاضغط على الزر أدناه لفتح الشاشة اللحظية داخل تيليجرام.\n\n📡 TradingView للشارت، وبيانات ReFo خارج الشارت تعرض مصدرها وحالتها بوضوح.",{inline_keyboard:[[{text:"🚀 فتح الشاشة اللحظية",web_app:{url}}]]});await send(e,c,"اختر أداة أخرى من القائمة عند الحاجة.",MENU)}
async function register(req,e){if(!token(e))return new Response("Missing Telegram bot token",{status:503});const o=new URL(req.url).origin,p={url:`${o}/telegram/webhook`,allowed_updates:["message"],drop_pending_updates:false};if(e.TELEGRAM_WEBHOOK_SECRET)p.secret_token=e.TELEGRAM_WEBHOOK_SECRET;const r=await fetch(api(e,"setWebhook"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)});return new Response(await r.text(),{status:r.status,headers:{"content-type":"application/json; charset=utf-8"}})}
async function status(e){if(!token(e))return Response.json({ok:false,error:"missing_token"},{status:503});const r=await fetch(api(e,"getWebhookInfo")),d=await r.json().catch(()=>({ok:false}));if(!r.ok)return Response.json({ok:false,error:"telegram_status_failed"},{status:502});const x=d.result||{};return Response.json({ok:!!d.ok,url:x.url||"",pending_update_count:x.pending_update_count||0,last_error_date:x.last_error_date||null,last_error_message:x.last_error_message||null})}
async function delegate(req,e,ctx,u,mapped){const b=structuredClone(u);if(b?.message&&mapped)b.message.text=mapped;const x=new URL(req.url);x.pathname="/telegram";x.search="";return legacyWorker.fetch(new Request(x.toString(),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)}),legacyEnv(e),ctx)}
async function webhook(req,e,ctx){if(!token(e))return new Response("Missing token",{status:503});if(e.TELEGRAM_WEBHOOK_SECRET&&req.headers.get("X-Telegram-Bot-Api-Secret-Token")!==e.TELEGRAM_WEBHOOK_SECRET)return new Response("Forbidden",{status:403});const u=await req.json().catch(()=>({})),m=u.message||{},c=String(m?.chat?.id||""),t=String(m?.text||"").trim();if(!c||!t)return Response.json({ok:true});const g=gate(e);if(g&&c!==String(g))return Response.json({ok:true});if(["/start","/menu","🏠 القائمة الرئيسية"].includes(t)){await showMenu(e,c);return Response.json({ok:true,feature:"reference-menu"})}if(["🖥️ الشاشة اللحظية","📊 الشاشة اللحظية"].includes(t)){await showLive(e,c);return Response.json({ok:true,feature:"live-screen"})}if(t==="💳 اشترك الآن / ترقية"){await send(e,c,"💳 <b>الاشتراك / الترقية</b>\n\nلا توجد بوابة دفع أو خطة اشتراك موثقة متصلة حاليًا؛ لذلك لن أعرض دفعًا أو اشتراكًا غير فعلي.",MENU);return Response.json({ok:true,feature:"subscription-disabled"})}const mapped=ALIASES.get(t)||t;return delegate(req,e,ctx,u,mapped)}
export default{async fetch(req,e,ctx){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/telegram/health")return Response.json({ok:true,service:BRAND,mode:"composite-webhook",legacy_routes:"preserved",tradingview_core:"delegated"});if(req.method==="GET"&&u.pathname==="/telegram/status")return status(e);if(req.method==="POST"&&u.pathname==="/telegram/register")return register(req,e);if(req.method==="POST"&&u.pathname==="/telegram/webhook")return webhook(req,e,ctx);return legacyWorker.fetch(req,legacyEnv(e),ctx)}};
