import app from "./timeframe_wrapper.js";

const VERSION="analysis-tools-v6-2026-09-14";
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function n(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):"-"}
function ema(vals,len){if(!vals.length)return[];const k=2/(len+1),out=[Number(vals[0])];for(let i=1;i<vals.length;i++)out.push(Number(vals[i])*k+out[i-1]*(1-k));return out}
function sma(vals,len){return vals.map((_,i)=>{const a=Math.max(0,i-len+1),s=vals.slice(a,i+1);return s.reduce((x,y)=>x+y,0)/s.length})}
function std(vals,len){return vals.map((_,i)=>{const a=Math.max(0,i-len+1),s=vals.slice(a,i+1),m=s.reduce((x,y)=>x+y,0)/s.length;return Math.sqrt(s.reduce((q,y)=>q+(y-m)*(y-m),0)/s.length)})}
function rsiSeries(vals,len=14){const out=new Array(vals.length).fill(50);for(let i=1;i<vals.length;i++){const a=Math.max(1,i-len+1);let g=0,l=0,c=0;for(let j=a;j<=i;j++){const d=vals[j]-vals[j-1];g+=Math.max(d,0);l+=Math.max(-d,0);c++}g/=Math.max(c,1);l/=Math.max(c,1);out[i]=l===0?100:100-100/(1+g/l)}return out}
function macdSeries(vals){const e12=ema(vals,12),e26=ema(vals,26),m=vals.map((_,i)=>e12[i]-e26[i]),sig=ema(m,9),hist=m.map((x,i)=>x-sig[i]);return{m,sig,hist}}
function aggregate(rows,size){if(size<=1)return rows.slice();const out=[];for(let i=0;i<rows.length;i+=size){const g=rows.slice(i,i+size);if(!g.length)continue;out.push({ts:g[0]?.ts,open:Number(g[0]?.open),high:Math.max(...g.map(x=>Number(x.high))),low:Math.min(...g.map(x=>Number(x.low))),close:Number(g.at(-1)?.close),volume:g.reduce((s,x)=>s+Number(x.volume||0),0)})}return out}
function frameRows(rows,tf){const b=Array.isArray(rows)?rows:[];return tf==="1W"?aggregate(b,5).slice(-55):b.slice(-55)}
function qurl(sym,tf,ind,tool){return `/dashboard?s=${encodeURIComponent(sym)}&tf=${encodeURIComponent(tf)}&ind=${encodeURIComponent(ind.join(','))}&tool=${encodeURIComponent(tool)}`}
function toggle(list,key){const s=new Set(list);s.has(key)?s.delete(key):s.add(key);return [...s]}
function indicatorPanel(rows,inds){if(rows.length<8)return"";const closes=rows.map(x=>Number(x.close)),rsi=rsiSeries(closes),macd=macdSeries(closes);const W=800,H=72,left=8,right=34,cw=W-left-right;let out='<div class="indicator-deck">';if(inds.includes('rsi')){const yy=v=>8+(100-v)/100*50,step=cw/(rsi.length-1||1);let path='';rsi.forEach((v,i)=>path+=(i?'L':'M')+(left+i*step).toFixed(1)+' '+yy(v).toFixed(1)+' ');out+=`<div class="indicator-row"><div class="ind-name">RSI 14 <b>${n(rsi.at(-1),1)}</b></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="0" x2="${W}" y1="${yy(70)}" y2="${yy(70)}" stroke="#5a3338" stroke-dasharray="3 3"/><line x1="0" x2="${W}" y1="${yy(30)}" y2="${yy(30)}" stroke="#284c3d" stroke-dasharray="3 3"/><path d="${path}" fill="none" stroke="#a277ff" stroke-width="1.5"/></svg></div>`}if(inds.includes('macd')){const vals=[...macd.m,...macd.sig,...macd.hist],mx=Math.max(...vals.map(v=>Math.abs(v)),.001),zero=36,step=cw/(closes.length-1||1),ys=v=>zero-v/mx*25;let pm='',ps='';macd.m.forEach((v,i)=>{pm+=(i?'L':'M')+(left+i*step).toFixed(1)+' '+ys(v).toFixed(1)+' ';ps+=(i?'L':'M')+(left+i*step).toFixed(1)+' '+ys(macd.sig[i]).toFixed(1)+' '});let bars='';macd.hist.forEach((v,i)=>{const x=left+i*step,y=ys(v),h=Math.abs(y-zero);bars+=`<rect x="${x-1.4}" y="${Math.min(y,zero)}" width="2.8" height="${Math.max(1,h)}" fill="${v>=0?'#26c68a':'#eb5a62'}" opacity=".65"/>`});out+=`<div class="indicator-row"><div class="ind-name">MACD 12,26,9 <b>${n(macd.m.at(-1),3)}</b></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="0" x2="${W}" y1="${zero}" y2="${zero}" stroke="#27313b"/>${bars}<path d="${pm}" fill="none" stroke="#48a8ff" stroke-width="1.25"/><path d="${ps}" fill="none" stroke="#f2b84b" stroke-width="1.15"/></svg></div>`}return out+'</div>'}
function analysisSummary(rows){if(rows.length<5)return{};const c=rows.map(x=>Number(x.close)),e20=ema(c,20).at(-1),e50=ema(c,50).at(-1),r=rsiSeries(c).at(-1),m=macdSeries(c),bbm=sma(c,20),s=std(c,20),up=bbm.at(-1)+2*s.at(-1),lo=bbm.at(-1)-2*s.at(-1),last=c.at(-1),vol=rows.at(-1)?.volume||0,av=rows.slice(-20).reduce((x,z)=>x+Number(z.volume||0),0)/Math.max(1,Math.min(20,rows.length));return{e20,e50,r,macd:m.m.at(-1),signal:m.sig.at(-1),hist:m.hist.at(-1),bbUpper:up,bbMid:bbm.at(-1),bbLower:lo,last,volRatio:av?Number(vol)/av:0}}
export default{async fetch(req,env,ctx){const u=new URL(req.url),res=await app.fetch(req,env,ctx);if(req.method!=="GET"||u.pathname!=="/dashboard")return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let html=await res.text();let state=null;try{state=env.STATE?await env.STATE.get("latest","json"):null}catch(_){state=null}const snap=state?.pro_engine_snapshot||{},details=Array.isArray(snap.details)?snap.details:[],sym=(u.searchParams.get('s')||snap?.top?.[0]?.symbol||'').toUpperCase(),tf=(u.searchParams.get('tf')||'1D').toUpperCase()==='1W'?'1W':'1D',t=details.find(x=>String(x.symbol||'').toUpperCase()===sym)||{},rows=frameRows(t.chart,tf);let inds=(u.searchParams.get('ind')||'ema,bb,rsi,macd,vol').split(',').filter(x=>['ema','bb','rsi','macd','vol'].includes(x));const tool=['none','trend','fib','sr'].includes(u.searchParams.get('tool'))?u.searchParams.get('tool'):'none',sum=analysisSummary(rows);
const css=`<style>.analysis-toolbar{height:36px;display:flex;align-items:center;gap:5px;padding:5px 8px;background:#0a0f14;border-bottom:1px solid #20262d;overflow:auto;white-space:nowrap}.anbtn{padding:5px 8px;border:1px solid #2a3540;background:#121920;color:#91a3b3;text-decoration:none;border-radius:3px;font-size:10px}.anbtn.on{background:#174f91;color:#fff;border-color:#2467b6}.anlabel{color:#657889;margin:0 3px}.indicator-deck{background:#070b0f;border-top:1px solid #20262d}.indicator-row{height:82px;position:relative;border-bottom:1px solid #171e25;padding-top:9px}.indicator-row svg{width:100%;height:68px;display:block}.ind-name{position:absolute;z-index:2;top:3px;right:8px;color:#8193a3;font-size:9px}.ind-name b{color:#dfe8ef;margin-right:5px}.analysis-box{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:#1c232b;border-top:1px solid #20262d}.analysis-cell{background:#0d1319;padding:6px 8px;text-align:center}.analysis-cell small{display:block;color:#6f8190}.analysis-cell b{display:block;color:#dfe7ee;margin-top:2px}.disabled-tool{opacity:.42}.toolhint{color:#ffd166;font-size:9px;margin-right:auto}@media(max-width:820px){.analysis-box{grid-template-columns:repeat(2,1fr)}} </style>`;html=html.replace('</head>',css+'</head>');
const keys=[['ema','EMA 20/50'],['bb','Bollinger'],['rsi','RSI'],['macd','MACD'],['vol','Volume']];const indicatorBtns=keys.map(([k,l])=>`<a class="anbtn ${inds.includes(k)?'on':''}" href="${qurl(sym,tf,toggle(inds,k),tool)}">${l}</a>`).join('');const toolBtns=[['none','Cursor'],['trend','Trend Line'],['fib','Fibonacci'],['sr','S/R Zones']].map(([k,l])=>`<a class="anbtn ${tool===k?'on':''}" href="${qurl(sym,tf,inds,k)}">${l}</a>`).join('');const toolbar=`<div class="analysis-toolbar"><span class="anlabel">Indicators</span>${indicatorBtns}<span class="anlabel">Tools</span>${toolBtns}<span class="anbtn disabled-tool" title="يحتاج تفاعل JavaScript مباشر">Crosshair</span><span class="anbtn disabled-tool">Text</span><span class="anbtn disabled-tool">Measure</span><span class="toolhint">${tool==='trend'?'Trend Line مفعّل':tool==='fib'?'Fibonacci مفعّل':tool==='sr'?'Support/Resistance Zones مفعّلة':''}</span></div>`;html=html.replace('<div class="chartbar">',toolbar+'<div class="chartbar">');
const deck=indicatorPanel(rows,inds);html=html.replace('<div class="indicators">',deck+'<div class="indicators">');
const aBox=`<div class="analysis-box"><div class="analysis-cell"><small>EMA20 / EMA50</small><b>${n(sum.e20)} / ${n(sum.e50)}</b></div><div class="analysis-cell"><small>Bollinger</small><b>${n(sum.bbLower)} — ${n(sum.bbUpper)}</b></div><div class="analysis-cell"><small>RSI 14</small><b>${n(sum.r,1)}</b></div><div class="analysis-cell"><small>MACD / Signal</small><b>${n(sum.macd,3)} / ${n(sum.signal,3)}</b></div><div class="analysis-cell"><small>Volume Ratio</small><b>${n(sum.volRatio,2)}x</b></div></div>`;html=html.replace('</section><aside class="right">',aBox+'</section><aside class="right">');
// Add visual overlay legend for server-side tools without pretending mouse drawing exists.
const overlay=`<div style="position:absolute;left:12px;top:12px;z-index:5;padding:5px 7px;background:#0b1118cc;border:1px solid #263441;border-radius:3px;color:#9fb0bf;font-size:9px">${tool==='trend'?'↗ Trend: آخر اتجاه خطي مرجعي':tool==='fib'?'Fib: 23.6% · 38.2% · 50% · 61.8%':tool==='sr'?'S/R: مستويات النظام مفعلة':'Chart Analysis'}</div>`;html=html.replace('<div class="chart">','<div class="chart" style="position:relative">'+overlay);
html=html.replace('</body>',`<div style="display:none">${VERSION}</div></body>`);const headers=new Headers(res.headers);headers.set('content-type','text/html; charset=UTF-8');headers.set('cache-control','no-store, no-cache, must-revalidate');return new Response(html,{status:res.status,headers})}};