const MAIN_KEYBOARD = {
  keyboard: [
    [{ text: "📊 الشاشة اللحظية" }, { text: "🎯 فرص اليوم" }],
    [{ text: "🔍 تحليل سهم" }, { text: "🧠 التحليل المتقدم" }],
    [{ text: "🟡 Golden Zone" }, { text: "🚀 الإشارات النشطة" }],
    [{ text: "🚨 تنبيهاتي" }, { text: "💼 محفظتي" }],
    [{ text: "📈 تقرير الأداء" }, { text: "🔮 فرص بكرة" }],
    [{ text: "🗺️ أداء القطاعات" }, { text: "🤖 المساعد الذكي" }],
    [{ text: "⚙️ الإعدادات" }]
  ], resize_keyboard: true, is_persistent: true
};
async function tg(env, method, payload={}) { if(!env.TOKEN) throw new Error("Missing TOKEN secret"); const r=await fetch(`https://api.telegram.org/bot${env.TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); const d=await r.json(); if(!d.ok) throw new Error(d.description||`Telegram ${method} failed`); return d.result; }
async function send(env,chatId,text,extra={}) { return tg(env,"sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,...extra}); }
function isAllowed(env,id){return !env.CHAT_ID||String(id)===String(env.CHAT_ID)}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function n(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):"-"}
async function loadState(env){if(!env.STATE)return null;try{return await env.STATE.get("latest","json")}catch(_){return null}}
function menuText(){return "🤖 <b>EGX Smart Scanner</b>\n\nمتصل عبر Cloudflare Worker Webhook.\nاختر من القائمة بالأسفل."}
function sourceNote(s){const x=s?.pro_engine_snapshot;if(!x)return "";const delayed=x.quote_mode&&x.quote_mode!=="LIVE";return `\n\n<i>${delayed?"⚠️ بيانات تقييم/متأخرة وليست لحظية للتنفيذ":"🟢 مصدر أسعار حي"}\nالمصدر: ${esc(x.quote_source||"-")}</i>`}
function plans(s){return Array.isArray(s?.trade_lifecycle?.plans)?s.trade_lifecycle.plans:[]}
function quality(p){const conf={HIGH:12,MEDIUM:7,LOW:2}[String(p.confidence||"").toUpperCase()]||0;const dist=Math.max(0,12-Math.min(12,Number(p.distance_to_trigger_pct||0)*2));const rr=Math.min(12,Number(p.rr_to_t1_now||0)*3);const liq=Math.min(10,Number(p.liquidity_score||0)/10);return Number(p.score||0)+conf+dist+rr+liq}
function marketWatchText(s){const snap=s?.pro_engine_snapshot;if(!snap)return "📊 <b>الشاشة اللحظية</b>\n\nلا توجد لقطة سوق مخزنة حتى الآن.";const r=snap.market_regime||{},top=Array.isArray(snap.top)?snap.top.slice(0,10):[];let out=`📊 <b>الشاشة اللحظية</b>\n\nالسوق: <b>${esc(r.name||"-")}</b>\nBreadth: ${n(r.breadth,1)}% | Avg Score: ${n(r.avg_score,1)}\nآخر تحديث: ${esc(snap.at||"-")}\n\n`;top.forEach((x,i)=>out+=`${i+1}. <b>${esc(x.symbol)}</b> ${n(x.price)} | Score ${n(x.score,0)} | ${esc(x.confidence||"-")}\n`);return out+sourceNote(s)}
function opportunitiesText(s){let a=plans(s).filter(p=>p.status==="WATCH").sort((a,b)=>quality(b)-quality(a)).slice(0,8);if(!a.length)return "🎯 <b>فرص اليوم</b>\n\nلا توجد خطط تداول مخزنة حاليًا.";let out="🎯 <b>أفضل فرص اليوم / WATCH</b>\n<i>الترتيب يجمع Score + الثقة + السيولة + القرب من التفعيل + RR</i>\n\n";a.forEach((p,i)=>{out+=`${i+1}. <b>${esc(p.symbol)}</b> — ${esc(p.status||"WATCH")} | ثقة ${esc(p.confidence||"-")}\n`;out+=`السعر ${n(p.price)} | تفعيل ${n(p.trigger)} | البعد ${n(p.distance_to_trigger_pct)}%\n`;out+=`وقف ${n(p.dynamic_stop??p.initial_stop)} | T1 ${n(p.target1)} | T2 ${n(p.target2)} | T3 ${n(p.target3)}\n`;out+=`Score ${n(p.score,0)} | RR→T1 ${n(p.rr_to_t1_now)} | سيولة ${n(p.liquidity_score,0)}\n\n`});return out+sourceNote(s)}
function goldenZoneText(s){let a=plans(s).filter(p=>p.status==="WATCH"&&Number(p.distance_to_trigger_pct)>=0&&Number(p.distance_to_trigger_pct)<=2.0).sort((a,b)=>Number(a.distance_to_trigger_pct)-Number(b.distance_to_trigger_pct));if(!a.length)return "🟡 <b>Golden Zone</b>\n\nلا توجد فرص قريبة بما يكفي من نقطة التفعيل حاليًا."+sourceNote(s);let out="🟡 <b>Golden Zone — قرب التفعيل</b>\n<i>WATCH داخل نطاق 2% من Trigger. ليست إشارة شراء قبل التفعيل بمصدر حي.</i>\n\n";a.slice(0,10).forEach((p,i)=>{out+=`${i+1}. <b>${esc(p.symbol)}</b> | السعر ${n(p.price)} → تفعيل ${n(p.trigger)}\n`;out+=`المسافة ${n(p.distance_to_trigger_pct)}% | RR ${n(p.rr_to_t1_now)} | Score ${n(p.score,0)} | ${esc(p.confidence||"-")}\n`;out+=`وقف ${n(p.dynamic_stop??p.initial_stop)} | T1 ${n(p.target1)}\n\n`});return out+sourceNote(s)}
function tomorrowText(s){const a=Array.isArray(s?.pro_engine_snapshot?.watchlist_next_session)?s.pro_engine_snapshot.watchlist_next_session.slice(0,10):[];if(!a.length)return "🔮 <b>فرص الجلسة القادمة</b>\n\nلا توجد قائمة حالية.";let out="🔮 <b>فرص الجلسة القادمة</b>\n\n";a.forEach((x,i)=>out+=`${i+1}. <b>${esc(x.symbol)}</b> | تفعيل ${n(x.trigger)} | وقف ${n(x.stop)} | Score ${n(x.score,0)}\n`);return out+sourceNote(s)}
function signalsText(s){const a=plans(s).filter(p=>p.status&&p.status!=="WATCH");if(!a.length)return "🚀 <b>الإشارات النشطة</b>\n\nلا توجد إشارات ENTRY نشطة حاليًا. البيانات المتأخرة تظل WATCH ولا تتحول إلى ENTRY."+sourceNote(s);let out="🚀 <b>الإشارات النشطة</b>\n\n";a.slice(0,10).forEach((p,i)=>out+=`${i+1}. <b>${esc(p.symbol)}</b> — ${esc(p.status)} | ${n(p.price)}\n`);return out+sourceNote(s)}
function stockText(s,symbol){const sym=symbol.toUpperCase(),p=plans(s).find(x=>String(x.symbol).toUpperCase()===sym),top=Array.isArray(s?.pro_engine_snapshot?.top)?s.pro_engine_snapshot.top:[],t=top.find(x=>String(x.symbol).toUpperCase()===sym);if(!p&&!t)return `🔍 لم أجد <b>${esc(sym)}</b> في آخر لقطة للمحرك.`;let out=`🔍 <b>تحليل ${esc(sym)}</b>\n\n`;if(p){out+=`الحالة: <b>${esc(p.status||"WATCH")}</b> | الثقة ${esc(p.confidence||"-")}\nالسعر: ${n(p.price)} | التفعيل: ${n(p.trigger)} | البعد: ${n(p.distance_to_trigger_pct)}%\nالوقف: ${n(p.dynamic_stop??p.initial_stop)}\nT1: ${n(p.target1)} | T2: ${n(p.target2)} | T3: ${n(p.target3)}\nScore: ${n(p.score,0)} | RR T1: ${n(p.rr_to_t1_now)} | سيولة: ${n(p.liquidity_score,0)}\n`}else out+=`السعر: ${n(t.price)} | Score: ${n(t.score,0)} | ثقة: ${esc(t.confidence||"-")}\n`;return out+sourceNote(s)}
async function handleMessage(env,m){const id=m?.chat?.id,text=(m?.text||"").trim();if(!id||!text||!isAllowed(env,id))return;if(text==="/start"||text==="/menu"||text==="⚙️ الإعدادات")return send(env,id,menuText(),{reply_markup:MAIN_KEYBOARD});if(text==="🔍 تحليل سهم")return send(env,id,"🔍 <b>تحليل سهم</b>\n\nاكتب مثلًا: <code>تحليل COMI</code>",{reply_markup:MAIN_KEYBOARD});const s=await loadState(env);if(text==="📊 الشاشة اللحظية")return send(env,id,marketWatchText(s),{reply_markup:MAIN_KEYBOARD});if(text==="🎯 فرص اليوم")return send(env,id,opportunitiesText(s),{reply_markup:MAIN_KEYBOARD});if(text==="🟡 Golden Zone")return send(env,id,goldenZoneText(s),{reply_markup:MAIN_KEYBOARD});if(text==="🔮 فرص بكرة")return send(env,id,tomorrowText(s),{reply_markup:MAIN_KEYBOARD});if(text==="🚀 الإشارات النشطة")return send(env,id,signalsText(s),{reply_markup:MAIN_KEYBOARD});if(/^تحليل\s+/i.test(text))return send(env,id,stockText(s,text.split(/\s+/).slice(1).join(" ")),{reply_markup:MAIN_KEYBOARD});const f={"🧠 التحليل المتقدم":"🧠 <b>التحليل المتقدم</b>\n\nسيتم ربط المؤشرات التفصيلية في المرحلة التالية.","🚨 تنبيهاتي":"🚨 <b>تنبيهاتي</b>\n\nربط إدارة التنبيهات مستمر.","💼 محفظتي":"💼 <b>محفظتي</b>\n\nربط المحفظة مستمر.","📈 تقرير الأداء":"📈 <b>تقرير الأداء</b>\n\nربط سجل الصفقات والأداء مستمر.","🗺️ أداء القطاعات":"🗺️ <b>أداء القطاعات</b>\n\nربط خريطة القطاعات مستمر.","🤖 المساعد الذكي":"🤖 <b>المساعد الذكي</b>\n\nسيتم ربط منطق القرار بعد اكتمال مزامنة الحالة."};return send(env,id,f[text]||"استخدم الأزرار من القائمة 👇",{reply_markup:MAIN_KEYBOARD})}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==="GET"&&(url.pathname==="/"||url.pathname==="/health"))return Response.json({ok:true,service:"EGX Smart Scanner Cloudflare Worker",state_binding:!!env.STATE});if(request.method==="GET"&&url.pathname==="/setup"){if(!env.TOKEN)return Response.json({ok:false,error:"TOKEN secret is missing"},{status:500});try{const webhookUrl=`${url.origin}/telegram`,result=await tg(env,"setWebhook",{url:webhookUrl,allowed_updates:["message"]});return Response.json({ok:true,webhook:webhookUrl,result})}catch(e){return Response.json({ok:false,error:String(e.message||e)},{status:500})}}if(request.method==="GET"&&url.pathname==="/webhook-info"){try{return Response.json({ok:true,info:await tg(env,"getWebhookInfo",{})})}catch(e){return Response.json({ok:false,error:String(e.message||e)},{status:500})}}if(request.method==="POST"&&url.pathname==="/sync"){if(!env.STATE)return Response.json({ok:false,error:"STATE KV binding is missing"},{status:500});if(!env.SYNC_SECRET)return Response.json({ok:false,error:"SYNC_SECRET is missing"},{status:500});if((request.headers.get("authorization")||"")!==`Bearer ${env.SYNC_SECRET}`)return Response.json({ok:false,error:"unauthorized"},{status:401});try{const body=await request.json();if(!body||typeof body!=="object")throw new Error("invalid state");await env.STATE.put("latest",JSON.stringify(body));return Response.json({ok:true,synced_at:new Date().toISOString()})}catch(e){return Response.json({ok:false,error:String(e.message||e)},{status:400})}}if(request.method==="GET"&&url.pathname==="/state-status"){const s=await loadState(env);return Response.json({ok:true,has_state:!!s,updated_at:s?.pro_engine_snapshot?.at||null,plans:plans(s).length})}if(request.method==="POST"&&url.pathname==="/telegram"){let u={};try{u=await request.json()}catch(_){}try{if(u.message)await handleMessage(env,u.message);return Response.json({ok:true})}catch(e){console.error(e);return Response.json({ok:false,error:"handler_failed"},{status:200})}}return new Response("Not found",{status:404})}};
