import base from "./index.js";

const SECTORS={ORHD:"عقارات",TMGH:"عقارات",MASR:"عقارات",PHDC:"عقارات",HELI:"عقارات",ETEL:"اتصالات",FWRY:"مدفوعات وتكنولوجيا مالية",EFIH:"مدفوعات وتكنولوجيا مالية",POUL:"أغذية",JUFO:"أغذية",DOMT:"أغذية",KABO:"منسوجات",ORWE:"منسوجات",SKPC:"بتروكيماويات",ABUK:"أسمدة وكيماويات",MFPC:"أسمدة وكيماويات",CCAP:"استثمارات",ALCN:"نقل ولوجستيات",SWDY:"صناعة ومعدات",COMI:"بنوك",CIEB:"بنوك",ADIB:"بنوك",EPCO:"رعاية صحية",CLHO:"رعاية صحية",ISPH:"رعاية صحية"};
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function n(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):"-"}
async function tg(env,text){const r=await fetch(`https://api.telegram.org/bot${env.TOKEN}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:env.CHAT_ID,text,parse_mode:"HTML"})});return r.ok}
function confidence(count){return count>=4?"عالية":count>=2?"متوسطة":"ضعيفة"}
function confidenceWeight(count){return count>=4?1:count>=2?.92:.82}
function sectorScore(r){const mom=Math.max(-10,Math.min(10,r.m5));const vol=Math.max(0,Math.min(3,r.vol));return r.score*0.72+(mom+10)*0.8+vol*4*confidenceWeight(r.count)}
function build(state){const top=Array.isArray(state?.pro_engine_snapshot?.top)?state.pro_engine_snapshot.top:[],groups={};for(const t of top){const sec=SECTORS[String(t.symbol||"").toUpperCase()]||"غير مصنف";(groups[sec]??=[]).push(t)}const rows=Object.entries(groups).map(([name,a])=>{const avg=k=>a.reduce((x,z)=>x+Number(z[k]||0),0)/a.length;const r={name,count:a.length,symbols:a.map(x=>x.symbol),score:avg("score"),m5:avg("momentum_5d"),m20:avg("momentum_20d"),vol:avg("volume_ratio")};r.rank=sectorScore(r);return r}).sort((a,b)=>b.rank-a.rank);let o="🗺️ <b>Sector Radar V2 — خريطة القطاعات الفنية</b>\n<i>ترتيب فني للعينة الحالية، وليس مؤشر قطاعات رسميًا من EGX. درجة الثقة تتأثر بعدد الأسهم الممثلة.</i>\n\n";rows.slice(0,10).forEach((r,i)=>{const icon=r.m5>2?"🟢":r.m5<0?"🔴":"🟡";o+=`${i+1}. ${icon} <b>${esc(r.name)}</b> — ثقة ${confidence(r.count)}\nالأسهم: ${esc(r.symbols.join(" • "))}\nAvg Score ${n(r.score,0)} | Mom5 ${n(r.m5)}% | Mom20 ${n(r.m20)}% | Vol ${n(r.vol)}x\nSector Rank ${n(r.rank,1)} | حجم العينة ${r.count}\n\n`});if(rows.length){const best=rows[0];o+=`<b>الأقوى فنيًا داخل العينة:</b> ${esc(best.name)}.`;if(best.count===1)o+=`\n⚠️ ممثل بسهم واحد (${esc(best.symbols[0])})؛ الثقة ضعيفة ولا يُعتبر حكمًا على القطاع بالكامل.`;else o+=`\nدرجة الثقة: <b>${confidence(best.count)}</b> بناءً على ${best.count} أسهم.`}const unknown=rows.find(x=>x.name==="غير مصنف");if(unknown)o+=`\n\n<i>غير مصنف حاليًا: ${esc(unknown.symbols.join(" • "))}. سيتم استكمال خريطة القطاعات تدريجيًا.</i>`;const snap=state?.pro_engine_snapshot;if(snap)o+=`\n\n<i>${snap.quote_mode!=="LIVE"?"⚠️ بيانات تقييم/متأخرة وليست لحظية للتنفيذ":"🟢 مصدر أسعار حي"}\nالمصدر: ${esc(snap.quote_source||"-")}</i>`;return o}
export default{async fetch(req,env,ctx){if(req.method==="POST"&&new URL(req.url).pathname==="/telegram"){let body;try{body=await req.clone().json()}catch(_){body=null}const text=body?.message?.text,chat=body?.message?.chat?.id;if(text==="🗺️ أداء القطاعات"&&(!env.CHAT_ID||String(chat)===String(env.CHAT_ID))){try{const state=env.STATE?await env.STATE.get("latest","json"):null;await tg(env,build(state));return Response.json({ok:true,sector_radar:"v2"})}catch(e){console.error(e);return Response.json({ok:false,error:"sector_radar_failed"},{status:200})}}}return base.fetch(req,env,ctx)}};
