import base from "./index.js";

const WORKER_VERSION="market-session-ui-v2.3-2026-09-14";
const SECTORS={ORHD:"عقارات",TMGH:"عقارات",MASR:"عقارات",PHDC:"عقارات",HELI:"عقارات",ETEL:"اتصالات",FWRY:"مدفوعات وتكنولوجيا مالية",EFIH:"مدفوعات وتكنولوجيا مالية",POUL:"أغذية",JUFO:"أغذية",DOMT:"أغذية",KABO:"منسوجات",ORWE:"منسوجات",SKPC:"بتروكيماويات",ABUK:"أسمدة وكيماويات",MFPC:"أسمدة وكيماويات",CCAP:"استثمارات",ALCN:"نقل ولوجستيات",SWDY:"صناعة ومعدات",COMI:"بنوك",CIEB:"بنوك",ADIB:"بنوك",EPCO:"رعاية صحية",CLHO:"رعاية صحية",ISPH:"رعاية صحية"};
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function n(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):"-"}
async function tg(env,chat,text){const r=await fetch(`https://api.telegram.org/bot${env.TOKEN}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chat,text,parse_mode:"HTML"})});return r.ok}
function confidence(count){return count>=4?"عالية":count>=2?"متوسطة":"ضعيفة"}
function confidenceWeight(count){return count>=4?1:count===3?.95:count===2?.88:.72}
function sectorScore(r){const mom5=Math.max(-10,Math.min(10,r.m5));const mom20=Math.max(-15,Math.min(15,r.m20));const vol=Math.max(0,Math.min(3,r.vol));const breadth=Math.max(0,Math.min(1,r.positiveShare));const raw=r.score*.58+(mom5+10)*.65+(mom20+15)*.28+vol*3.2+breadth*8;return raw*confidenceWeight(r.count)}
function sessionLabel(status){return{SESSION:"🟢 الجلسة مفتوحة",PRE_MARKET:"🟠 ما قبل الجلسة",CLOSED:"⚫ السوق مغلق",WEEKEND:"🔒 عطلة أسبوعية"}[status]||status||"-"}
function buildMarket(state){const x=state?.pro_engine_snapshot;if(!x)return"📊 <b>آخر لقطة سوق</b>\n\nلا توجد لقطة سوق مخزنة.";const r=x.market_regime||{},ses=x.market_session||{},a=Array.isArray(x.top)?x.top.slice(0,10):[],live=x.quote_mode==="LIVE";let o=`📊 <b>${live?"الشاشة اللحظية":"آخر لقطة سوق — تقييم غير لحظي"}</b>\n\nالسوق: <b>${esc(r.name||"-")}</b> | الحالة: <b>${esc(sessionLabel(ses.status))}</b>\nBreadth: ${n(r.breadth,1)}% | Avg Score: ${n(r.avg_score,1)}\nآخر تحديث للنموذج: ${esc(x.at||"-")}\n`;if(!live)o+=`⚠️ الأسعار المعروضة ليست Live وقد تمثل آخر بيانات تقييم متاحة.\n`;o+="\n";a.forEach((z,i)=>o+=`${i+1}. <b>${esc(z.symbol)}</b> ${n(z.price)} | Score ${n(z.score,0)} | ${esc(z.confidence||"-")}\n`);if(ses.heuristic)o+=`\n<i>ساعة الجلسة تقديرية: ما قبل الجلسة ${esc(ses.pre_market_from||"09:30")}، الجلسة ${esc(ses.session_from||"10:00")}–${esc(ses.session_to||"14:30")} بتوقيت القاهرة، ولا تشمل العطلات الرسمية بعد.</i>`;o+=`\n\n<i>${live?"🟢 مصدر أسعار حي":"⚠️ بيانات تقييم/متأخرة وليست لحظية للتنفيذ"}\nالمصدر: ${esc(x.quote_source||"-")}\nالإصدار: ${WORKER_VERSION}</i>`;return o}
function build(state){const top=Array.isArray(state?.pro_engine_snapshot?.top)?state.pro_engine_snapshot.top:[],groups={};for(const t of top){const sec=SECTORS[String(t.symbol||"").toUpperCase()]||"غير مصنف";(groups[sec]??=[]).push(t)}const rows=Object.entries(groups).map(([name,a])=>{const avg=k=>a.reduce((x,z)=>x+Number(z[k]||0),0)/a.length;const r={name,count:a.length,symbols:a.map(x=>x.symbol),score:avg("score"),m5:avg("momentum_5d"),m20:avg("momentum_20d"),vol:avg("volume_ratio"),positiveShare:a.filter(x=>Number(x.momentum_5d||0)>0).length/a.length};r.rank=sectorScore(r);return r}).sort((a,b)=>b.rank-a.rank);let o="🗺️ <b>Sector Radar V2.2 — خريطة القطاعات الفنية</b>\n<i>ترتيب فني للعينة الحالية، وليس مؤشر قطاعات رسميًا من EGX. الترتيب يخص العينة فقط، وثقته تتأثر بعدد الأسهم الممثلة.</i>\n\n";if(!rows.length)return o+"لا توجد بيانات قطاعية كافية.";rows.slice(0,10).forEach((r,i)=>{const icon=r.m5>2?"🟢":r.m5<0?"🔴":"🟡";o+=`${i+1}. ${icon} <b>${esc(r.name)}</b> — ثقة ${confidence(r.count)}\nالأسهم: ${esc(r.symbols.join(" • "))}\nAvg Score ${n(r.score,0)} | Mom5 ${n(r.m5)}% | Mom20 ${n(r.m20)}% | Vol ${n(r.vol)}x\nإيجابية العينة ${n(r.positiveShare*100,0)}% | Sector Rank ${n(r.rank,1)} | حجم العينة ${r.count}\n`;if(r.count===1)o+=`⚠️ قطاع ممثل بسهم واحد فقط؛ لا يُعمم الحكم على القطاع.\n`;o+="\n"});const ranked=rows.filter(r=>r.name!=="غير مصنف");const reliable=ranked.filter(r=>r.count>=2);const best=(reliable.length?reliable:ranked)[0];if(best){o+=`<b>الأقوى فنيًا داخل العينة${reliable.length?" مع أفضلية للقطاعات متعددة الأسهم":""}:</b> ${esc(best.name)}\nدرجة الثقة: <b>${confidence(best.count)}</b> | ممثل بـ ${best.count} سهم.`;if(!reliable.length)o+=`\n⚠️ لا يوجد قطاع في العينة الحالية ممثل بسهمين أو أكثر، لذلك المقارنة القطاعية ضعيفة.`}const unknown=rows.find(x=>x.name==="غير مصنف");if(unknown)o+=`\n\n<i>غير مصنف حاليًا: ${esc(unknown.symbols.join(" • "))}.</i>`;const snap=state?.pro_engine_snapshot;if(snap)o+=`\n\n<i>${snap.quote_mode!=="LIVE"?"⚠️ بيانات تقييم/متأخرة وليست لحظية للتنفيذ":"🟢 مصدر أسعار حي"}\nالمصدر: ${esc(snap.quote_source||"-")}\nالإصدار: ${WORKER_VERSION}</i>`;return o}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/sector-version")return Response.json({ok:true,worker_version:WORKER_VERSION,main:"src/sector_enhanced.js"});if(req.method==="POST"&&u.pathname==="/telegram"){let body;try{body=await req.clone().json()}catch(_){body=null}const text=body?.message?.text,chat=body?.message?.chat?.id;if((text==="🗺️ أداء القطاعات"||text==="📊 الشاشة اللحظية")&&(!env.CHAT_ID||String(chat)===String(env.CHAT_ID))){try{const state=env.STATE?await env.STATE.get("latest","json"):null;await tg(env,chat,text==="📊 الشاشة اللحظية"?buildMarket(state):build(state));return Response.json({ok:true,feature:text==="📊 الشاشة اللحظية"?"market-snapshot-v2.3":"sector-radar-v2.2",worker_version:WORKER_VERSION})}catch(e){console.error(e);return Response.json({ok:false,error:"enhanced_view_failed"},{status:200})}}}return base.fetch(req,env,ctx)}};
