import app from "./stock_panel_wrapper.js";

const VERSION = "tradingview-core-v8-terminal-api-2026-09-17";
const TV_SRC = "https://s3.tradingview.com/tv.js";
const UI_ORIGIN = "https://refogx-pro.folkhero3.workers.dev";
function safeSymbol(v){const s=String(v||"").toUpperCase().replace(/[^A-Z0-9_.-]/g,"");return s||"COMI"}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function arr(v){return Array.isArray(v)?v.map(x=>String(x)).slice(0,12):[]}
function cors(){return{"access-control-allow-origin":UI_ORIGIN,"access-control-allow-methods":"GET, OPTIONS","access-control-allow-headers":"Content-Type","cache-control":"no-store","vary":"Origin"}}
function cleanPlan(p={}){return{signal_id:p.signal_id??null,status:p.status??null,trigger:num(p.trigger),stop:num(p.stop),t1:num(p.t1),t2:num(p.t2),t3:num(p.t3),rr_to_t1_now:num(p.rr_to_t1_now),distance_to_trigger_pct:num(p.distance_to_trigger_pct)}}
function terminalPayload(state){const snap=state?.pro_engine_snapshot||{},details=Array.isArray(snap.details)?snap.details:(Array.isArray(snap.top)?snap.top:[]),plans=Array.isArray(state?.trade_lifecycle?.plans)?state.trade_lifecycle.plans:[],pmap=Object.fromEntries(plans.map(p=>[safeSymbol(p?.symbol),p]));return{ok:true,source:"ReFo Engine",asof:snap.asof||snap.updated_at||state?.updated_at||null,quote_mode:snap.quote_mode||"UNKNOWN",market_session:snap.market_session||{},market_regime:snap.market_regime||{},stocks:details.map(t=>{const symbol=safeSymbol(t?.symbol);return{symbol,sector:t?.sector??null,price:num(t?.price),score:num(t?.score),liquidity_score:num(t?.liquidity_score),volume_ratio:num(t?.volume_ratio),momentum_5d:num(t?.momentum_5d),rsi:num(t?.rsi),adx:num(t?.adx),why:arr(t?.why),setups:arr(t?.setups),plan:cleanPlan(pmap[symbol]||{})}})}}
function tvPage(sym,test=false){const status=test?'<div id="status">جاري اختبار تحميل TradingView…</div>':'';const inset=test?'36px 0 0 0':'0';return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ReFo TradingView</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#05070a;color:#dce3ea;font-family:Tahoma,Arial,sans-serif}#status{position:fixed;top:0;left:0;right:0;z-index:5;padding:8px 12px;background:#101720;border-bottom:1px solid #263443;font-size:12px}#tv{position:absolute;inset:${inset}}.ok{color:#2ecc71}.bad{color:#ff6b6b}</style></head><body>${status}<div id="tv"></div><script>(()=>{const st=document.getElementById('status');function msg(t,c){if(st){st.textContent=t;st.className=c||''}}const s=document.createElement('script');s.src=${JSON.stringify(TV_SRC)};s.async=true;s.onload=()=>{if(!window.TradingView||typeof window.TradingView.widget!=='function'){msg('تم تحميل tv.js لكن TradingView.widget غير متاح','bad');return}msg('تم تحميل TradingView بنجاح','ok');try{new window.TradingView.widget({autosize:true,symbol:'EGX:${sym}',interval:'D',timezone:'Africa/Cairo',theme:'dark',style:'1',locale:'ar_AE',toolbar_bg:'#090d12',enable_publishing:false,hide_side_toolbar:false,allow_symbol_change:true,save_image:false,container_id:'tv',studies:['MASimple@tv-basicstudies','Volume@tv-basicstudies']})}catch(e){msg('TradingView widget error: '+(e&&e.message?e.message:String(e)),'bad')}};s.onerror=()=>msg('فشل تحميل tv.js من s3.tradingview.com','bad');document.head.appendChild(s)})();</script><div style="display:none">${VERSION}</div></body></html>`}
export default{async fetch(req,env,ctx){const url=new URL(req.url);if(req.method==="OPTIONS"&&url.pathname==="/api/refo-terminal")return new Response(null,{status:204,headers:cors()});if(req.method==="GET"&&url.pathname==="/api/refo-terminal"){let state=null;try{state=env.STATE?await env.STATE.get("latest","json"):null}catch(_){state=null}if(!state?.pro_engine_snapshot)return new Response(JSON.stringify({ok:false,error:"snapshot_unavailable",source:"ReFo Engine"}),{status:503,headers:{...cors(),"content-type":"application/json; charset=UTF-8"}});return new Response(JSON.stringify(terminalPayload(state)),{headers:{...cors(),"content-type":"application/json; charset=UTF-8"}})}if(req.method==="GET"&&(url.pathname==="/tv-test"||url.pathname==="/tv-frame")){const sym=safeSymbol(url.searchParams.get("s"));return new Response(tvPage(sym,url.pathname==="/tv-test"),{headers:{"content-type":"text/html; charset=UTF-8","cache-control":"no-store"}})}const res=await app.fetch(req,env,ctx);if(req.method!=="GET"||url.pathname!=="/dashboard")return res;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return res;let html=await res.text(),state=null;try{state=env.STATE?await env.STATE.get("latest","json"):null}catch(_){state=null}const snap=state?.pro_engine_snapshot||{},details=Array.isArray(snap.details)?snap.details:[],requested=safeSymbol(url.searchParams.get("s")),sym=details.some(x=>safeSymbol(x?.symbol)===requested)?requested:safeSymbol(snap?.top?.[0]?.symbol||requested);html=html.replace(/<script[^>]+src=["']https:\/\/s3\.tradingview\.com\/tv\.js["'][^>]*><\/script>/gi,'').replace(/function initTV\(\)[\s\S]*?window\.addEventListener\("DOMContentLoaded", initTV\);/g,'');const css=`<style id="refo-tv-core-style">.center{display:flex!important;min-width:0!important;overflow:hidden!important;background:#05070a!important;padding:0!important;position:relative!important}.center>*:not(#refo_tv_frame){display:none!important}#refo_tv_frame{display:block!important;position:absolute!important;inset:0!important;border:0!important;width:100%!important;height:100%!important;min-height:560px!important;background:#05070a!important;z-index:50!important}</style>`;html=html.replace("</head>",css+"</head>");const frame=`<iframe id="refo_tv_frame" title="TradingView EGX Chart" src="/tv-frame?s=${encodeURIComponent(sym)}&v=8" loading="eager"></iframe>`;const a=html.indexOf('<section class="center"'),b=a!==-1?html.indexOf('<aside class="right"',a):-1;if(a!==-1&&b!==-1){const e=html.indexOf('>',a);if(e!==-1)html=html.slice(0,e+1)+frame+'</section>\n'+html.slice(b)}html=html.replace("</body>",`<div style="display:none">${VERSION}</div></body>`);const headers=new Headers(res.headers);headers.set("content-type","text/html; charset=UTF-8");headers.set("cache-control","no-store, no-cache, must-revalidate");return new Response(html,{status:res.status,headers})}};